import React, { useEffect, useMemo, useState } from "react";
import PageHeader from "../components/common/PageHeader";
import Button from "../components/common/Button";
import { TableSkeleton } from "../components/common/Skeleton";
import EmptyState from "../components/common/EmptyState";
import AlertFilters from "../components/alerts/AlertFilters";
import AlertTable from "../components/alerts/AlertTable";
import { BellIcon, RefreshIcon } from "../components/common/Icons";
import { getAlerts } from "../services/alertApi";

const defaultFilters = {
  search: "",
  severity: "all",
  status: "all",
  eventType: "all",
  camera: "all",
  date: "all",
};

function SummaryCard({ label, value, counterClass }) {
  return (
    <div className="card flex items-center gap-4 p-4">
      <p className={`text-3xl font-bold ${counterClass}`}>{value}</p>
      <p className="text-sm font-medium text-slate-600">{label}</p>
    </div>
  );
}

function Alerts() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [filters, setFilters] = useState(defaultFilters);

  const load = () => {
    setLoading(true);
    setError(false);
    getAlerts()
      .then((res) => setAlerts(res.data))
      .catch(() => setError(true))
      .finally(() => setLoading(false));
  };

  useEffect(load, []);

  const cameras = useMemo(
    () => [...new Set(alerts.map((a) => a.camera).filter(Boolean))].sort(),
    [alerts]
  );

  const summary = useMemo(() => {
    const sev = (s) => alerts.filter((a) => a.severity === s).length;
    const active = alerts.filter((a) =>
      ["new", "active"].includes((a.status || "").toLowerCase())
    ).length;
    return {
      totalActive: active,
      critical: sev("critical"),
      high: sev("high"),
      medium: sev("medium"),
      acknowledged: alerts.filter(
        (a) => (a.status || "").toLowerCase() === "acknowledged"
      ).length,
    };
  }, [alerts]);

  const filtered = useMemo(() => {
    const q = filters.search.trim().toLowerCase();
    return alerts
      .filter((a) => {
        if (filters.severity !== "all" && a.severity !== filters.severity) return false;
        if (filters.status !== "all" && (a.status || "").toLowerCase() !== filters.status) return false;
        if (filters.eventType !== "all" && a.eventType !== filters.eventType) return false;
        if (filters.camera !== "all" && a.camera !== filters.camera) return false;
        if (
          q &&
          !`${a.id} ${a.eventType} ${a.camera} ${a.cameraName} ${a.location}`
            .toLowerCase()
            .includes(q)
        )
          return false;
        return true;
      })
      .sort((a, b) => (b.riskScore || 0) - (a.riskScore || 0));
  }, [alerts, filters]);

  // Date filter (client-side over mock data; a real backend would apply it server-side)
  const applyDate = (list) => {
    const now = new Date();
    if (filters.date === "24h")
      return list.filter((a) => now - new Date(a.timestamp) <= 24 * 60 * 60 * 1000);
    if (filters.date === "7d")
      return list.filter((a) => now - new Date(a.timestamp) <= 7 * 24 * 60 * 60 * 1000);
    return list.filter((a) => new Date(a.timestamp).toDateString() === now.toDateString());
  };

  const visibleList = useMemo(() => {
    if (filters.date === "all") return filtered;
    return applyDate(filtered);
  }, [filtered, filters.date]);

  return (
    <div>
      <PageHeader
        title="Alerts"
        subtitle="Review and manage prioritized security incidents generated by the surveillance system."
      >
        <Button variant="secondary" size="sm" onClick={load}>
          <RefreshIcon size={15} /> Refresh
        </Button>
      </PageHeader>

      {/* Summary cards */}
      <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">
        <SummaryCard label="Total Active" value={summary.totalActive} counterClass="text-slate-900" />
        <SummaryCard label="Critical" value={summary.critical} counterClass="text-red-700" />
        <SummaryCard label="High" value={summary.high} counterClass="text-red-600" />
        <SummaryCard label="Medium" value={summary.medium} counterClass="text-orange-600" />
        <SummaryCard label="Acknowledged" value={summary.acknowledged} counterClass="text-yellow-600" />
      </div>

      {/* Filter bar */}
      <div className="card mt-6 p-4">
        <AlertFilters filters={filters} onChange={setFilters} cameras={cameras} />
      </div>

      {/* Main list */}
      <div className="mt-6">
        <h2 className="mb-4 text-base font-semibold text-slate-800">
          Active & Recent Alerts
        </h2>

        {loading ? (
          <TableSkeleton rows={6} cols={7} />
        ) : error ? (
          <EmptyState
            tone="error"
            icon={<BellIcon size={22} />}
            title="Unable to load alerts."
            description="There was a problem fetching alert data. Please try again."
            action={
              <Button variant="secondary" size="sm" onClick={load}>
                <RefreshIcon size={15} /> Retry
              </Button>
            }
          />
        ) : visibleList.length ? (
          <>
            <p className="mb-4 text-sm text-slate-500 dark:text-slate-400">
              Showing{" "}
              <span className="font-medium text-slate-700 dark:text-slate-200">
                {visibleList.length}
              </span>{" "}
              of {alerts.length} alerts
            </p>
            <AlertTable alerts={visibleList} />
          </>
        ) : (
          <EmptyState
            icon={<BellIcon size={22} />}
            title="No alerts found"
            description="No security alerts match the selected filters."
            action={
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setFilters(defaultFilters)}
              >
                Clear filters
              </Button>
            }
          />
        )}
      </div>
    </div>
  );
}

export default Alerts;
